morph-data/docs

- data-application/en/input-component-date-picker.mdx
- data-application/en/input-component-date-range-picker.mdx
- data-application/en/input-component-input.mdx
- data-application/en/input-component-select.mdx
- data-application/en/mdx/mdx-2-styling.mdx
- data-application/ja/mdx/mdx-2-styling.mdx
- mint.json
Fix components docs for v0.1.0
> Fix components docs for v0.1.0

- data-application/en/input-component-date-picker.mdx
- data-application/en/input-component-date-range-picker.mdx
- data-application/ja/input-component-date-picker.mdx
- data-application/ja/input-component-date-range-picker.mdx
- mint.json
update global menu & fix examples
> update global menu & fix examples

- docs/en/deploy/deploy.mdx
- docs/ja/deploy/deploy.mdx
> fix deployment steps

- data-application/en/data-component-metrics.mdx
- data-application/ja/data-component-metrics.mdx
- docs/en/getting-started/why-morph.mdx
- docs/ja/getting-started/why-morph.mdx
- mint.json
fix documentations for components docs 0.1.0
> fix documentations for components docs 0.1.0

- docs/en/deploy/deploy.mdx
- docs/ja/deploy/deploy.mdx
> fix: deploy process order

- mint.json
- reference/en/cli-commands/context.mdx
- reference/ja/cli-commands/context.mdx
added morph context command to reference section
> feat: morph context

- reference/en/cli-commands/config.mdx
- reference/ja/cli-commands/config.mdx
- Updated the usage of `morph config` and its parameter `--profile`
> update: morph config

- reference/en/cli-commands/clean.mdx
- reference/ja/cli-commands/clean.mdx
This PR introduces `--force` parameter for `morph clean` command.
> Update morph clean Command Options

- docs/ja/develop/tutorials/chatbot.mdx
- reference/en/morph_lib/stream/stream_chat.mdx
- reference/ja/morph_lib/stream/create_chunk.mdx
- reference/ja/morph_lib/stream/stream_chat.mdx
> add stream_chat

- docs/en/getting-started/quickstart.mdx
- docs/en/getting-started/why-morph.mdx
- docs/ja/getting-started/quickstart.mdx
- Fix wrong translations
- Fix wrong example codes
> v0.1.2 fixes

- docs/en/deploy/deploy.mdx
- docs/en/getting-started/quickstart.mdx
- docs/ja/deploy/deploy.mdx
- docs/ja/getting-started/quickstart.mdx
Fix langchain demo & docker requirement
> Fix langchain demo & docker requirement

- docs/en/getting-started/quickstart.mdx
- docs/ja/getting-started/quickstart.mdx
> Fix typo on quick start

- docs/en/getting-started/quickstart.mdx
- docs/ja/getting-started/quickstart.mdx
fix code in jp & video url
none
> fix code in jp & video url

- docs/en/quickstart/building-app.mdx
- docs/ja/quickstart/building-app.mdx
- fix indents for quickstart python code
> fix indents for quickstart python code

- docs/en/develop/guides/alias.mdx
- docs/ja/develop/guides/alias.mdx
- fix sample code in alias section
data -> loadData
none
> fix sample code in alias section

- docs/en/develop/guides/building-frontend.mdx
- docs/en/quickstart/deploy.mdx
- docs/ja/quickstart/deploy.mdx
- reference/en/python/morph-func.mdx
- reference/ja/python/morph-func.mdx
update deployment steps & remove unused params
none
> update deployment steps & remove unused params

- mint.json
- reference/en/morph_lib/ai/text_to_html.mdx
- reference/en/morph_lib/ai/text_to_markdown.mdx
- reference/en/morph_lib/ai/text_to_matplotlib.mdx
- reference/en/morph_lib/ai/text_to_plotly.mdx
- reference/en/morph_lib/ai/text_to_sql.mdx
- reference/ja/morph_lib/ai/text_to_html.mdx
- reference/ja/morph_lib/ai/text_to_markdown.mdx
- reference/ja/morph_lib/ai/text_to_matplotlib.mdx
- reference/ja/morph_lib/ai/text_to_plotly.mdx
- reference/ja/morph_lib/ai/text_to_sql.mdx
add stream_chat & make morph_lib.ai deprecated
none
> add stream_chat & make morph_lib.ai deprecated

- data-application/en/ai-component-llm.mdx
- data-application/en/mdx/shadcn-ui.mdx
- data-application/ja/ai-component-llm.mdx
- data-application/ja/mdx/shadcn-ui.mdx
- mint.json
> Add shadcn & side-by-side

- data-application/en/advanced-morph-data-basic.mdx
- data-application/ja/advanced-morph-data-basic.mdx
> Update API https method

- reference/en/python/morph-variables.mdx
- reference/ja/python/morph-load_data.mdx
- reference/ja/python/morph-variables.mdx
- add `default` and `required` params for @morph.variables.
> Fill the missing params for  @morph.variables.

- docs/en/advanced/llm.mdx
- docs/en/develop/tutorials/chat_sidebyside.mdx
- docs/en/develop/tutorials/chatbot.mdx
- docs/en/develop/tutorials/plotly.mdx
- docs/en/develop/tutorials/pygwalker.mdx
- docs/en/quickstart/building-app.mdx
- docs/ja/advanced/llm.mdx
- docs/ja/develop/tutorials/chat_sidebyside.mdx
- docs/ja/develop/tutorials/chatbot.mdx
- docs/ja/develop/tutorials/plotly.mdx
- docs/ja/develop/tutorials/pygwalker.mdx
- docs/ja/quickstart/building-app.mdx
Added sample install command of uv and poetry
> Added sample install command of uv and poetry

- docs/en/quickstart/deploy.mdx
- docs/ja/quickstart/deploy.mdx
- Added video for github integration
none
> Added video for github integration

- docs/en/advanced/migration-guide.mdx
- docs/en/quickstart/deploy.mdx
- docs/ja/advanced/migration-guide.mdx
- docs/ja/quickstart/deploy.mdx
- reference/en/framework/morph-project.mdx
- reference/ja/framework/morph-project.mdx
> add updates for v0.3.0

- docs/en/develop/guides/building-frontend.mdx
- docs/ja/develop/guides/building-frontend.mdx
- mint.json
- Reorganize components section
> Feature/components 0.3.0

- docs/en/advanced/migration-guide.mdx
- docs/ja/advanced/migration-guide.mdx
- add: frontend migration guide for 0.2 → 0.3
> add: frontend migration guide for 0.2 → 0.3
